<?php
    foreach ($this->creepThumbs['img'] as $value) { ?>
        <li>
            <a class="<?php echo $value['affilation']; ?> creepsSprite unitIcon ti <?php echo $this->stringManipulator()->strtocamelcase($value['name']); ?>PrevIcon" href="<?php echo $this->url()?>/<?php echo $value['fname']; ?>" title="<?php echo $value['name']; ?>" ><?php echo $value['name']; ?></a>
        </li>
    <?php }
?>
