<div class="graveyard clearfix">
	<h2>The Secret of the Graveyard</h2>
	<a href="<?php echo $this->baseUrl('/files/frontend/img/enUS/media/big/FBF-Graveyard.jpg'); ?>" rel="colorbox" class="colorboxImages graveyardImage">
		<img width="550"
			src="<?php echo $this->baseUrl('/files/frontend/img/enUS/media/medium/FBF-Graveyard.jpg'); ?>"
			title="The Graveyard"
			data-description="The Graveyard">
	</a>
	<p>
		<span class="firstChar">F</span>
		or the Forsaken, the Graveyard is not a place of sorrow but of happiness. It's not where they bury their dead but where they are given life. It's where they meet long gone friends or the enemies they fought the night before. The Graveyads have become sacred places for them and digging for corpses is a sort of daily ceremony. They are key strategic points for the Forsaken's success  and must always be well protected.<br />
		The old history tomes found in the Hidden Library of the Forsaken Bastion speak of an ancient race: the Dragons. Majestic creatures that helped the Gods in creating the world. That could fly through the skies with ease and speed. Creatures that could burn a forest or make the driest desert bloom with flowers. Darker tomes speak of Ghauzar, the Death Dragon and, more importantly, how to bring him back to life. The Wizard Cáligo knew about this book long before and has finally unleashed it's power. Ghauzar, the Wizard's new pet, has been given the sacred task of protecting the Bastion's graveyard.<br /><br /> 
		Beware of the Wingless Dragon because neither sword or arrow will hurt him. Beware in the graveyard for Ghauzar creeps below. Beware of the dark tome's warning: a dead dragon cannot be killed again.
	</p>
</div>