<div class="kingMithas clearfix">
	<h2>King Mithas</h2>
	<a href="<?php echo $this->baseUrl('/files/frontend/img/enUS/media/big/FBF-king-marco-mithas.jpg'); ?>" rel="colorbox" class="colorboxImages mithasImage">
		<img width="300"
			src="<?php echo $this->baseUrl('/files/frontend/img/enUS/media/medium/FBF-king-marco-mithas.jpg'); ?>"
			title="King Marco Mithas"
			data-description="King Marco Mithas">
	</a>
	<p>
		<span class="firstChar">U</span>
		nknowingly, the spiritual father of the Forsaken. King Marco Mithas of the Kingdom d'Or, tricked by the Wizard Cáligo and cursed to eternal undeath. The Undead King, the richest man at his time and the proudest. Father to Marco Vas, whose soul was later fused with the Wizard's into The Heart that commands the dead.
		<br />
		King Mithas stands in the way to the heart, both to protect his master and his kingdom. Like all the creatures that reside the Bastion, his body has been greatly changed by putrefaction and black magic. His physical strenght and magic prowess were enhanced by Cáligo himself. More than once, the Fallen King has been sent to the frontlines and has proven a great asset to the Forsaken. But as the war is taken to the very core of the Forsaken's land, the Heart has appointed Mithas as his personal guard.
		<br /><br />
		Your men may beat the towers at the Bastion Gates. They may repel the Death Dragon protecting the graveyard. They may defeat the Broodmother and her children. They may push the elite heroes of the Forsaken, but their tired flesh won't stand against the Undying King. And don't be fooled, he'll be back.
	</p>
</div>