<div class="titanDevourer clearfix">
	<h2>Titan Devourer</h2>
	<a href="<?php echo $this->baseUrl('/files/frontend/img/enUS/media/big/FBF-titan-devourer.jpg'); ?>" rel="colorbox" class="colorboxImages titanImage">
		<img width="250"
			src="<?php echo $this->baseUrl('/files/frontend/img/enUS/media/medium/FBF-titan-devourer.jpg'); ?>"
			title="Titan Devourer"
			data-description="Titan Devourer">
	</a>
	<p>
		<span class="firstChar">T</span>
		he Great Library was among the mightiest structures in the old Kingdom. During its construction, workers reported that they found an unknown artifact buried near the foundation. The chanced discovery fascinated and scared King Mithas at the same time. The uncertainty that lied within the artifact intimidated the king and he issued an investigation prohibition and ordered it hidden away in the Library where it was originally found. Those unfortunate enough to know about this event were all killed to prevent any possible leak of information. Despite all the measures taken to prevent the secret from being discovered, the kingdom could never foresee its harbinger of doom. The Wizard’s unholy conquest not only granted him the throne but also access to hidden documents available only to the king. Among them was the only map in the whole realm that showed where the fabled Great Library was.
		<br /><br />
		The Wizard subsequently organized and directly led the expedition to explore the secret that the kingdom once vehemently protected. However, the Wizard was unable to anticipate how perilous the journey would be. Only he alone managed to reach the Library’s ancient gates. What he discovered inside the deepest chamber was a tome that contained the ritual to summon an eldritch horror from an extra dimensional realm to follow one’s biddings.
		<br />
		Nothing is known about this abomination save for the single fact that it guards the path leading to the Forsaken Heart. Some speculate that it is an illusion that kills mentally. Others say that it is a thousand damned entities materializing on this plane. One thing is certain, no one has ever returned once he ventured inside…
	</p>
</div>