<p class="glossaryWelcomeText"> 
    Here is a list of the most used words in our game is "<strong>Forsaken Bastion's Fall</strong> (FBF)". There sure are a lot more. 
    See also tB_Viper's English-Polish Glossary <a href="http://van2002.w.interia.pl/wc3ft/glossary.htm" target="_blank" >here</a>. 
    Please be aware this page was created by companies and individuals that are neither affiliated with nor supported by Blizzard Entertainment
    or <a href="/">forsaken-bastions-fall.com</a>, and the views and opinions expressed in these guides do not necessarily reflect our own.
</p>
<div class="jScrollbar">
    <div class="bgTop absolute"></div>
    <div class="jScrollbar_mask fll relative">
        <div class="glossaryContainer a-d active">
            <?php echo $this->render("glossary/a-d.phtml"); ?>
        </div>
        <div class="glossaryContainer e-h" style="display:none;">
            <?php echo $this->render("glossary/e-h.phtml"); ?>
        </div>
        <div class="glossaryContainer i-l" style="display:none;">
            <?php echo $this->render("glossary/i-l.phtml"); ?>
        </div>
        <div class="glossaryContainer m-p" style="display:none;">
            <?php echo $this->render("glossary/m-p.phtml"); ?>
        </div>
        <div class="glossaryContainer q-t"style="display:none;">
            <?php echo $this->render("glossary/q-t.phtml"); ?>
        </div>
        <div class="glossaryContainer u-x" style="display:none;">
            <?php echo $this->render("glossary/u-x.phtml"); ?>
        </div>
        <div class="glossaryContainer y-z" style="display:none;">
            <?php echo $this->render("glossary/y-z.phtml"); ?>
        </div>
    </div>
    <div class="bgBottom absolute"></div>
    <div class="jScrollbar_draggable fll">
        <a href="#" class="draggable"></a>
    </div>
    <div class="clearfix"></div>
</div>

<ul class="glossaryPagination">
    <li class="a-d">A-D</li>
    <li class="e-h">E-H</li>
    <li class="i-l">I-L</li>
    <li class="m-p">M-P</li>
    <li class="q-t">Q-T</li>
    <li class="u-x">U-X</li>
    <li class="y-z">Y-Z</li>
</ul>



