<div class="about">
	<h6><small>FBF Team presents</small></h6>
	<h3>Forsaken Bastion's Fall</h3>
	<br />
	<br />
	<table class="gameStats">
		<thead>
			<tr>
				<th>Map Info</th>
				<th>FBF Team</th>
				<th>Beta Tester</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>
					Type: <b>Tower Defense + Aeon of Strife</b><br />
					Category: <b>Miscellanous / Other</b><br />
					Map Size: <b>160 x 160</b><br />
					Recommended players: <b>10-12</b><br />
					Estimated gameplay time: <b>1 - 1.5h</b><br />
					Tileset: <b>Felwood</b><br />
					File Size: <b>4.27MB</b><br />
					Doodads: <b>~16.500</b><br />
					Lines of Code: <b>~42.000</b><br />
					Number of Heroes: <b>27</b><br />
					Buyable Items: <b>120</b><br />
					Towers: <b>11</b>
				</td>
				<td>
					Leader: <a target="_blank" href="http://www.hiveworkshop.com/forums/members/pred1980/">pred1980</a><br />
					Writers: <a target="_blank" href="http://www.hiveworkshop.com/forums/members/dzerpic/">DZerpic</a> / <a target="_blank" href="http://www.hiveworkshop.com/forums/members/doomlord/">Doomlord</a><br />
					Terrain: <a target="_blank" href="http://www.hiveworkshop.com/forums/members/situ/">Situ</a><br />
					Triggering:<br />
					- pred1980<br />
					- <a target="_blank" href="http://www.hiveworkshop.com/forums/members/alienatsystem/">Alien@System</a><br />
					- <a target="_blank" href="http://www.hiveworkshop.com/forums/members/kricz/">Kricz</a><br />
					- <a target="_blank" href="http://warcraft.ingame.de/forum/member.php?u=354541" rel="nofollow">nzca</a><br />
					- <a target="_blank" href="http://www.hiveworkshop.com/forums/members/looking_for_help/">looking_for_help</a><br />
					<br />
					Artist: <a target="_blank" href="http://vaejoun.deviantart.com/" rel="nofollow">Vaejoun</a> / <a target="_blank" href="http://www.hiveworkshop.com/forums/members/justicebringer/">Justicebringer</a><br />
					Forum Moderator: : <a target="_blank" href="http://www.hiveworkshop.com/forums/members/chaosy/">chaosy</a> / <a target="_blank" href="http://www.hiveworkshop.com/forums/members/drunken_jackal/">drunken_jackal</a><br />
					Others: <a target="_blank" href="http://www.hiveworkshop.com/forums/members/peq/">peq</a>
				</td>
				<td>
					<a target="_blank" href="http://www.hiveworkshop.com/forums/members/jonhysone/">jonhysone (Hive)</a><br />
					<a target="_blank" href="http://www.hiveworkshop.com/forums/members/i_am_death/">I_am_Death (Hive)</a><br />
					<a target="_blank" href="http://forsaken-bastions-fall.com/forums/User-zlowly" rel="nofollow">zlowly (FBF)</a><br />
					<a target="_blank" href="http://forsaken-bastions-fall.com/forums/User-bhusta" rel="nofollow">bhusta (FBF)</a><br />
				</td>
			</tr>
		</tbody>
	</table>
	<br />
	<div class="facebookAndBugReport">
		
		<a target="_blank" href="https://www.facebook.com/F0rsaken.Bastions.Fall" rel="nofollow">
			<img alt="Find us on Facebook" src="<?php echo $this->baseUrl('/files/frontend/img/enUS/misc/FB-FindUsOnFacebook.png'); ?>" width="144" height="37">
		</a>
		<br />
		<br />
		<a href="http://www.moddb.com/mods/forsaken-bastions-fall" title="View Forsaken Bastion's Fall on Mod DB" target="_blank"><img src="http://button.moddb.com/popularity/medium/mods/23884.png" alt="Forsaken Bastion's Fall" /></a>
		<br />
		<br />
		<a class="hive" target="_blank" href="http://www.hiveworkshop.com/forums/map-development-202/forsaken-bastions-fall-242443/">
		    <img alt="Forsaken Bastion's Fall" src="<?php echo $this->baseUrl('/files/frontend/img/enUS/misc/hiveLogo.jpg'); ?>" width="50" height="50">
		</a>
		<br />
		<br />
		<strong>Bug Report</strong>
		<br />
		<a target="_blank" href="http://forsaken-bastions-fall.com/forums/Forum-FBF-Report-Bugs" rel="nofollow">http://forsaken-bastions-fall.com/fo...BF-Report-Bugs</a>
	</div>
	<br />
	<br />
	<strong><h4>Overview</h4></strong>
	<p>
		Forsaken Bastion's Fall (FBF) is a map that combines Tower Defense gameplay with an AoS-like Hero PvP Battle. Our project started in 2008, when it was known as Defense of the Undead (DotU). As time went on, ideas, criticizing, and suggestions reshaped DotU into a whole new map which was then completely remade from scratch to become what it is now.<br />
		<br />
		FBF is set in a completely new universe with an extensive lore that keeps growing as time goes by. It is set in a key point of the World's history: At the very end of a long war that present many great changes at social, political and religious levels. The players can choose from 2 teams and 5 different factions. The Forsaken, an ancient cult of necromancers and it's undead army, have to defend their last fortress from The Alliance (The Infidel), a coalition of human nations using their last resources to take down the Forsaken.<br />
		<br />
		There is a total of 5 factions, 27 heroes, 104 items (8 base items and 24 items unique to each faction), 27 minions with varied statistics and skills, and 11 towers for the Forsaken to use. Alongside a great map terrain and an extensive lore.<br />
	</p>
	<br />
	<strong><h4>The Plot</h4></strong>
	<p>
		<i>
			"I have seen it in the mud covered face of the southern men; I have seen it in the warmongering northerns, and even in the god's forgotten, dead plagued army. It is Change..."
		</i>
		<br />
		-Brother Baritos, Philosopher and Travelling Monk of the 'Twin Suns Church'
		<br />
		<br />
		For almost twenty years, war has plagued the Seneca Region: a peninsula divided by several nations and cultures essentially different one from the other. The original conflict between two major kingdoms triggered devastating events, as new religious and political groups rose to power. New technologies led to new philosophies and new ways of life, new ways to experience the world and new ways to rule society. The Seneca Region is in a state of change.<br />
		<br />
		Amidst the chaos of change and the evolving societies, an old demon returned to the land. A Wizard, the last member of a forgotten cult long thought to have been vanquished, executed a master plan to raise an undead army and enforce his twisted, necromantic black magic upon the world. He calls himself Cáligo, the Last of The Forsaken.<br />
		<br />
		Cáligo entered the court of King Marco Mithas, a man whose greed was as big as his vast wealth. The naive King was easily tricked by the Wizard who cast a curse on him and his new born son, Marco Vas. Cáligo raised the Prince into his puppet, thus ruling the Kindom from the shadows. To channel the energies that would raise the undead, it was necessary to have a healthy, strong body able to resist the powerful spell. Cáligo would transfer his soul from his frail carcass to Vas's younger form. But Vas proved to be a fighter as he resisted the Wizard's power. The invisible struggle that took place between them caused the Prince's body to implode, leaving in place his beating hurt covered by the Wizard's magic.<br />
		<br />
		Despite the outcome, the Heart raised an army of undead and executed it's campaign of terror over the exhausted people of the Seneca Region that had been fighting each other for years. The Prince's resistance was a major setback in Cáligo's plans, but what ultimately caused his defeat was 'change'. During the time he was executing his plan, the ways to wage war changed radically in the Region; new weapons that could make a simple peasant beat an expert swordman were readily available and, in the end, the Forsaken were pushed back.<br />
		<br />
		Now, the Heart awaits deep within it's Bastion and the tired champions of the endless war stand at the gates, ready to vanquish The Forsaken once and for all. Undoubtedly, this battle will end the war as both sides put everything at stake. The last champions of the Alliance and The Last of The Forsaken. The winner takes all.<br />
		<br />
		<b>
			<i>You can download the complete lore <a target="_blank" href="<?php echo $this->baseUrl('/files/frontend/img/enUS/misc/FBF-Lore.pdf'); ?>" rel="nofollow">here</a>.</i>
		</b>
	</p>
	<br />
	<strong><h4>Gameplay and Mechanics</h4></strong>
	<p>
		Forsaken Bastion's Fall is a multiplayer map that pits two sides, of up to 6 players each, one against the other. One of the teams, The Forsaken, has to defend the fortress from the Alliance team that's trying to reach the end and destroy the source of magic that keeps the defenders alive. <br />
		<br />
		The players start in the Tower Defense stage, where The Forsaken team has to strategically place a series of diferent towers to stop the Alliance and it's waves of minions from reaching the entrance. The total number of waves is limited to 20 so the Alliance players need to end this stage as quickly as possible.<br />
		<br />
		When the Alliance reaches the Bastion's Gates, the AoS stage begins. Here is when the Forsaken players take control of their chosen heroes. Alonside minions of their own and NPC Forsaken Bosses, they will have to defend the corridors of the stronghold from the Alliance's efforts to reach the end. The Alliance wins if they do so within the 20 minion waves, and the Forsaken win if they succesfully defeat all waves before their enemies complete their goal.<br />
	</p>
	<br />
	<strong><h4>Tower Defense</h4></strong>
	<p>
		The tower defense is the first part of every wave and is solely played by the Undead. The Infidel can not interfere with the actions of the Undead players in that area. The defense strength is designed, and their HP and numbers are adjusted so that this number is achieved no matter how many Undead players there are in the game.<br />
		<br />
		The towers are pretty standard towers you will see in most TDs, mostly meant for dealing damage, and only a handful have special abilities and effects.<br />
		<br />
		The towers are paid in wood, which is given to the players at the end of every round and can not be obtained in another way.<br />
	</p>
	<br />
	<strong><h4>Hero Battle</h4></strong>
	<p>
		Once the Alliance players reach the entrance of the fortress, the second stage begins. The Forsaken players now control their own heroes and all playable character statistics are rebalanced to fit the stage. The Alliance players will have a tougher time dealing with their enemies, as they not only face player heroes but, also, the Forsaken minion waves and a set number of bosses. Even more, the wave count keeps getting lower and if it reaches 0, the Alliance will lose.<br />
		<br />
		Things don't get easier for the defending players as they lose the protection of the towers and run the risk of being vulnerable to their enemy's attacks.<br />
	</p>
	<br />
	<strong><h4>Teams and Factions</h4></strong>
	<p>
		<h5><b>The Forsaken and The Heart:</b></h5><br />
		The defending players play for The Forsaken: A vast undead army controlled by the last of an ancient necromantic cult. They have at their choosing a total of 13 Undead-themed heroes. Before it was corrupted by the wizard Cáligo, it was known as the Kingdom d'Or, the Golden Kingdom. King Marco Mithas was the supreme ruler, and the wealthiest man of his time. Yet, his vanity and greed allowed Cáligo to trick him and transform the Kingdom of Gold into his base of operations. <br />
		<br />
		The Forsaken find themselves pushed all the way back to their last Bastion, yet they are willing to die for their master's cause and have several weapons and tricks at their disposal. They are all experienced fighters and mischievous tacticians, empowered by the Black magic that gives them life; a dangerous combination to face.<br />
		<br />
		<h5><b>The Alliance:</b></h5><br />
		The Alliance is formed by 3 major factions: The Second Regnum, the Order of the Moon and the Bel'Trama. Additionally, there's a group of mercenaries ready to take the glory of victory for the highest bidder.<br />
		<br />
		<b>The Second Regnum. Of Knights and Honour:</b><br />
		<br />
		The Second Regnum traces it's origins back to the settlers that baptized the land. A long time ago, the Crown owned all the land in the Peninsula. It's society is highly religious and conservative, defined by traditions and a feudal system that have remained intact for centuries, but the recent events and the rise of new powers have shaken the Regnum's very foundations.<br />
		<br />
		One of the few things that keep the Kingdom together is religion. The only dogma allowed by the state is that of the Church of the Twin Suns, firmly constructed upon the idea of two opposite but complimentary parental Gods. The Church and the State are always keen on enforcing rules and laws upon the 'people' to keep them under control, but these are often bent or overlooked for a fair amount of gold.<br />
		<br />
		<h5><b>The Bel'Trama. Outlanders:</b></h5><br />
		<i>"Men fear what is new and unknown, that which is foreign to their own personal worlds, 	they fear that which is bigger and stronger than them. When men feel threatened and cornered by this things they fear, they treat them with disdain and hostility."</i><br />
		~Brother Baritos, Philosopher and Travelling Monk of the 'Twin Suns Church' about the Outlanders.<br />
		<br />
		Men in the Peninsula fear the Bel'Trama for this reasons. A colossal mass of Green-skinned men and manlike animals. Foreign and unknown, they are different in every aspect to the common man. They are called the Outlanders, among other names, because their home is far across the mountains to the north and the seas to the east.<br />
		<br />
		Their existence has been known for only a few decades and it has finished the age-long debate among the Regnum's philosophers as to whether or not the world extends beyond the known land. But the Bel'trama are regarded as wild barbarians, uneducated beasts ready to strike and take the peninsula with their vast army of primitives. Yet, the Bel'Trama have done nothing to earn this reputation as they, as a matter of fact, have ignored all attempts to establish a relationship by the Peninsula's nations.<br />
		<br />
		Despite all of this, the Bel'Trama kept a close eye to the war that ravaged the Seneca Region and have witnessed from afar the rise of the Forsaken. For reasons unknown, they launched an invasion on Forsaken territory, pushing them back and aiding the Heart's enemies. Still unsure, the Regnum agreed to an alliance with the Outlanders but only to defeat their common foe.<br />
		<br />
		<h5><b>The Order of the Moon:</b></h5><br />
		They are a cult of magic-wielders located in the 'Luna' island, south of the Peninsula, territory of the Second Regnum. Only recently they made their existence public by preaching the coming of The End and The Rebirth.<br />
		<br />
		They believe time in a cyclical form of time that starts with the birth of an all-seeing Goddess and her giving birth to Man and all the creatures. The cycles end with men repenting and their souls returning back to the Goddess. This fatalistic belief has found an enemy in the Church of the Twin Suns, and so, the Order is seen as a threat by the Second Regnum.<br />
		<br />
		Their leader claims to have been sent by the Goddess to save as many as possible from the inevitable End, and guide them 'back to her womb'. Whether her intentions are good or not remains to be seen. Despite the criticism the Order receives, it has gained many followers in the southern provinces and many more have flocked to their numbers now that they have made themselves public and raised arms against the army of undead.<br />
		<br />
		As with the Bel'Trama, the Regnum has deemed necessary to establish a temporary alliance with the Order to defeat the Forsaken.<br />
	</p>
	<br />
	<strong><h4>Features</h4></strong>
	<table class="featureStats">
		<tbody>
			<tr>
				<td>
					<a target="_blank" href="http://forsaken-bastions-fall.com/heroes" rel="nofollow">Heroes</a>
				</td>
				<td><b>primary standard heroes but with unique abilities</b></td>
			</tr>
			<tr>
				<td>
					<a target="_blank" href="http://forsaken-bastions-fall.com/items" rel="nofollow">Items</a>
				</td>
				<td><b>32 items per race divided into Basic, Advanced and Ancient with a lot of special abilities</b></td>
			</tr>
			<tr>
				<td>
					<a target="_blank" href="http://forsaken-bastions-fall.com/creeps" rel="nofollow">Creeps</a>
				</td>
				<td><b>27 different creeps which are spread over 20 rounds</b></td>
			</tr>
			<tr>
				<td>
					<a target="_blank" href="http://forsaken-bastions-fall.com/towers" rel="nofollow">Towers</a>
				</td>
				<td><b>11 Towers divided into 3 types, the common, rare and unique towers. All Towers can be upgraded 3 times and the majority have different abilities</b></td>
			</tr>
			<tr>
				<td>Gameplay</td>
				<td><b>it's a unique gameplay experience because FBF combines two of the most popular genre -The TD and AoS-</b></td>
			</tr>
			<tr>
				<td>Terrain</td>
				<td><b>with great attention to detail the terrain was created over several months and offer the player a dark and creepy atmosphere</b></td>
			</tr>
		</tbody>
	</table>
	<br />
	<strong><h4>Host Bots</h4></strong>
	<p>
		You can play Forsaken Bastion's Fall on our 5 Host Bots. <br />
		Just click  <a target="_blank" href="http://forsaken-bastions-fall.com" rel="nofollow">here</a> and copy the game name from the table. <br />
		<br />
		<b>Join your Warcraft 3 TFT and have fun!</b><br />
		<br />
	</p>
</div>