<p class="terms absolute">
    Terms and Conditions | <a href="/" title="Official FBF Website">© <?php echo date("Y"); ?> forsaken-bastions-fall.com</a> | All Rights Reserved
</p>
<p class="blizzard absolute">
    Warcraft® III: Reign of Chaos™ | ©2002 <a href="http://www.blizzard.com" title="Blizzard Entertainment">Blizzard Entertainment</a>, Inc.. All rights reserved. Reign of Chaos is a trademark and Warcraft and Blizzard Entertainment are trademarks or registered trademarks of Blizzard Entertainment, Inc. in the U.S. and/or other countries.
</p>
<nav class="absolute footerNavi clearfix">
    <a href="<?php echo $this->baseUrl('heroes');?>" title="FBF Heroes">Heroes</a>
    <a href="<?php echo $this->baseUrl('items');?>" title="FBF Items">Items</a>
    <a href="<?php echo $this->baseUrl('creeps');?>" title="FBF Creeps">Creeps</a>
    <a href="<?php echo $this->baseUrl('towers');?>" title="FBF Towers">Towers</a>
    <a href="<?php echo $this->baseUrl('mechanics');?>" title="FBF Mechanics">Mechanics</a>
    <a href="<?php echo $this->baseUrl('forums');?>" title="FBF Forums">Forums</a>
    <a href="<?php echo $this->baseUrl('download');?>" title="FBF Download">Download</a>
</nav>
<a href="https://www.facebook.com/F0rsaken.Bastions.Fall" target="_blank" title="Become A Fan" class="fanpage mainSprite">fanpage</a>
<a class="moddb" href="http://www.moddb.com/mods/forsaken-bastions-fall" title="View Forsaken Bastion's Fall on Mod DB" target="_blank">
    <img src="http://media.moddb.com/images/global/moddb.png" alt="Forsaken Bastion's Fall" width="30" height="30" />
</a>
<a class="hive" target="_blank" href="http://www.hiveworkshop.com/forums/map-development-202/forsaken-bastions-fall-242443/">
    <img alt="Forsaken Bastion's Fall" src="<?php echo $this->baseUrl('/files/frontend/img/enUS/misc/hiveLogo.jpg'); ?>" width="30" height="30">
</a>
<a href="http://rocarena.com/np/" target="_blank" title="RoCArena.com" class="rocarena mainSprite ti">RoCArena.com</a>